# Generated by Django 5.2.11 on 2026-03-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='amulya',
            new_name='Member',
        ),
    ]
